version: '3'

services:
  web:
    image: lgdlivepool/comm-node:latest
    command: ./django_start
    links:
      - redis
    volumes:
      - nodedb:/db
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DB_PATH=${DB_PATH}
      - CELERY_BROKER=${CELERY_BROKER}
      - CELERY_BACKEND=${CELERY_BACKEND}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}

  celery_beat:
    image: lgdlivepool/comm-node:latest
    command: celery -A easyerp worker --beat -S django -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - nodedb:/db
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DB_PATH=${DB_PATH}
      - CELERY_BROKER=${CELERY_BROKER}
      - CELERY_BACKEND=${CELERY_BACKEND}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: redis:7-alpine

volumes:
  nodedb: