name: Stage Deployment
on:
  push:
    branches: ["stage"]
    paths-ignore:
      - 'Cloudformation/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    name: Docker image generation
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Check out code
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          ref: stage
          
      # - uses: satackey/action-docker-layer-caching@v0.0.11
      #   # Ignore the failure of a step and avoid terminating the job.
      #   continue-on-error: true
      # - run: docker build --tag easyerp:prod-${{ github.sha }} .
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - run: docker build --tag easyerp:stage-${{ github.sha }} .
      
      # - name: Docker Build
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     tags: easyerp:prod-${{ github.sha }}
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      - name: List Docker images
        run: docker images
        
      
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-2
          local-image: easyerp:stage-${{ github.sha }}
          image: easyerp:stage-${{ github.sha }}, easyerp:stage-latest
      
  deploy:
    name: Deploy to ECS
    environment: Staging
    runs-on: ubuntu-latest
    steps:
      - uses: chrislennon/action-aws-cli@v1.1
        # All commands after this point have access to the AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - run: aws ecs update-service --cluster EasyERP-Stage --service EasyERP-Stage --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        
          
