name: Unit Test
on: [pull_request] # activates the workflow when there is a push or pull request in the repo
jobs:
  test_project:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      # - run: sudo apt-get install build-essential libssl-dev libffi-dev python3.11-dev
      - run: pip install --upgrade pip
      # - run: pip install pycryptodome
      - run: pip install -r requirements.txt #--use-pep517 # install all our dependencies for the project
      - run: pytest . # run pytest test
        env:
          DEVENV: dev
