name: Unit Test
on:
  pull_request:
    types: [opened, reopened, synchronize] # activates the workflow when there is a push or pull request in the repo
jobs:
  test_project:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: sudo apt-get install -y build-essential python3-dev libev-dev
      - run: pip install --upgrade pip
      - run: pip install Cython
      # - run: pip install pycryptodome
      - run: pip install wheel
      - run: pip install -r requirements.txt #--use-pep517 # install all our dependencies for the project
      - run: pytest . # run pytest test
        env:
          DEVENV: dev
